### ISSUE TITLE
Question about the baseline IPTransE results in paper

### ISSUE THREAD

**Issue by iamlockelightning** [nju-websoft/BootEA#1]
Hi, Zequn.
I try to use https://github.com/thunlp/IEAJKE(IPTransE) to reproduce the results of IPTransE on DBP15Kzh-en. But the results are so much bad than what reported in your paper BootEA(My results are Hit@1: 0.1941, Hit@10: 0.4685, MRR: 0.2833). I just changed the data format of the DBP15Kzh-en to what IPTransE needs. No parameters modified.
Would you like to share some advice on it? (Or kindly would you like to share the code/input_dataset that you use?)
Thanks!

**Comment by sunzequn** [comment]
The results of IPTransE on DBP15K were produced using my own implementation because there was no official code at that time.  I would suggest you to try more parameter settings, such as the similarity threshold.

**Comment by iamlockelightning** [comment]
Thank you for your reply!! And I saw the e-mail just now. 
Yes, I found that the iteration predicted many false pairs, but it was hard to control the threshold dynamically. I will try on. 
Thanks again!
