### ISSUE TITLE
数据中的疑虑

### ISSUE THREAD

**Issue by situjie68** [nju-websoft/BootEA#4]
hello,你好，最近在膜拜你写的BootEA代码，不过对于其中使用到的数据有个小问题，请教下哈：ref_ent_ids和sup_ent_ids之间的区别是什么呢，感觉好像都是对齐种子？

**Comment by sunzequn** [comment]
不是的。sup_ent_ids是已知的对齐pair，训练时候监督用的；而ref_ent_ids是测试时候用的。
